/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si;
import Controladores.Controladorventa;
import Controladores.Controlador_Report_pdf;
import Controladores.Controlador_capturar_resultados;
import Modelos.Modelo_capturar_resultados;
/**
 *
 * @author Alexis
 */
public class Capturar_resultados extends javax.swing.JFrame {
public static boolean seagregoexterno=false;
 static SI cc= new SI();
    /**
     * Creates new form Entradaproductos
     */
public Capturar_resultados(int id_venta_a_capturar_resultados){
    Controlador_capturar_resultados.id_a_actualizar_resultados=id_venta_a_capturar_resultados; //Aqui se guarda el id de la venta de a cual se van a actualizar los datos
    Modelo_capturar_resultados.id_paciente(Controlador_capturar_resultados.id_a_actualizar_resultados);
} 
    public Capturar_resultados() {
        initComponents();
        Controladorventa.noduplicar_capturaresultados=true;
        Controlador_capturar_resultados.metodos_al_iniciar_entradasproductos0(Controlador_capturar_resultados.id_a_actualizar_resultados);//Aqui se envia al controlador el id para traer todos los datos para capturar los resultados
        id_venta.setText(String.valueOf(Controlador_capturar_resultados.id_a_actualizar_resultados));
        id_paciente.setText(String.valueOf(Controlador_capturar_resultados.id_paciente));
        
         this.setLocation(30, 0); // CENTRAR FORMULARIO
         envio_email.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar_articulo = new javax.swing.JPanel();
        producto_sobrante3 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtable_ProductosEntradas = new javax.swing.JTable();
        fecha_hora_ingreso = new javax.swing.JLabel();
        id_venta = new javax.swing.JLabel();
        paciente = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        fecha_nacimiento = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        genetrar_Pdf = new javax.swing.JButton();
        gastos_btn_back = new javax.swing.JButton();
        envio_email = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        id_paciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        agregar_articulo.setBackground(new java.awt.Color(0, 51, 102));
        agregar_articulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregar_articulo.setDoubleBuffered(false);
        agregar_articulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        producto_sobrante3.setBackground(new java.awt.Color(135, 193, 193));
        producto_sobrante3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        producto_sobrante3.setDoubleBuffered(false);
        producto_sobrante3.setLayout(null);

        jPanel31.setBackground(new java.awt.Color(135, 193, 193));

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel83.setText("Captura de resultados");

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/salir-flecha-derecha (1).png"))); // NOI18N
        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jButton10)
                .addContainerGap(673, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        producto_sobrante3.add(jPanel31);
        jPanel31.setBounds(0, 0, 1288, 74);

        jPanel33.setBackground(new java.awt.Color(135, 193, 193));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jtable_ProductosEntradas = new javax.swing.JTable(){
            public boolean isCellEditable(int filas, int columnas){
                if(columnas==1){
                    return true;
                }else{
                    return false;
                }
            }
        };
        Jtable_ProductosEntradas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jtable_ProductosEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Jtable_ProductosEntradas);

        jPanel33.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 530, 200));

        fecha_hora_ingreso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fecha_hora_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        fecha_hora_ingreso.setText("dbFecha_ingreso:");
        jPanel33.add(fecha_hora_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 230, -1));

        id_venta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        id_venta.setForeground(new java.awt.Color(255, 255, 255));
        id_venta.setText("idVenta:");
        jPanel33.add(id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        paciente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paciente.setForeground(new java.awt.Color(255, 255, 255));
        paciente.setText("dbPaciente:");
        jPanel33.add(paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 430, -1));

        edad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        edad.setForeground(new java.awt.Color(255, 255, 255));
        edad.setText("dbEdad:");
        jPanel33.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, -1));

        sexo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sexo.setForeground(new java.awt.Color(255, 255, 255));
        sexo.setText("dbSexo:");
        jPanel33.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, -1));

        fecha_nacimiento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fecha_nacimiento.setForeground(new java.awt.Color(255, 255, 255));
        fecha_nacimiento.setText("dbFecha_nacimiento:");
        jPanel33.add(fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 260, -1));

        jLabel80.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Venta:");
        jPanel33.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, -1));

        jLabel81.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Paciente:");
        jPanel33.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        jLabel82.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Edad:");
        jPanel33.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, -1));

        jLabel84.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Sexo:");
        jPanel33.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        jLabel85.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Fecha_nacimiento:");
        jPanel33.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, -1));

        jLabel75.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Fecha_ingreso:");
        jPanel33.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, -1));

        genetrar_Pdf.setBackground(new java.awt.Color(255, 255, 255));
        genetrar_Pdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genetrar_Pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/pdf.png"))); // NOI18N
        genetrar_Pdf.setText("Generar PDF");
        genetrar_Pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genetrar_PdfActionPerformed(evt);
            }
        });
        jPanel33.add(genetrar_Pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 160, 50));

        gastos_btn_back.setBackground(new java.awt.Color(255, 255, 255));
        gastos_btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gastos_btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/salir-flecha-derecha (1).png"))); // NOI18N
        gastos_btn_back.setText("Regresar");
        gastos_btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastos_btn_backActionPerformed(evt);
            }
        });
        jPanel33.add(gastos_btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 150, 50));

        envio_email.setBackground(new java.awt.Color(255, 255, 255));
        envio_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        envio_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/email.png"))); // NOI18N
        envio_email.setText("Enviar Email");
        envio_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envio_emailActionPerformed(evt);
            }
        });
        jPanel33.add(envio_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 170, 50));

        jLabel86.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("No. paciente");
        jPanel33.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, -1));

        id_paciente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        id_paciente.setForeground(new java.awt.Color(255, 255, 255));
        id_paciente.setText("idVenta:");
        jPanel33.add(id_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 120, -1));

        producto_sobrante3.add(jPanel33);
        jPanel33.setBounds(10, 80, 600, 620);

        agregar_articulo.add(producto_sobrante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Controladorventa.botones_salir();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void gastos_btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastos_btn_backActionPerformed
       dispose();
    }//GEN-LAST:event_gastos_btn_backActionPerformed

    private void genetrar_PdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genetrar_PdfActionPerformed
        // GENERANDO PDF DE LCIENTES
      Controlador_Report_pdf n = new Controlador_Report_pdf();
      n.Generacion_PDF_client(); // llamando el metodo con el obj          
    }//GEN-LAST:event_genetrar_PdfActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controladorventa.noduplicar_capturaresultados=false;
    }//GEN-LAST:event_formWindowClosed

    private void envio_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envio_emailActionPerformed
        Envio_email mail = new Envio_email();
        mail.setVisible(true);
        Envio_email.File.setText(Controlador_Report_pdf.nom);
    }//GEN-LAST:event_envio_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturar_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturar_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturar_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturar_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturar_resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Jtable_ProductosEntradas;
    public static javax.swing.JPanel agregar_articulo;
    public static javax.swing.JLabel edad;
    public static javax.swing.JButton envio_email;
    public static javax.swing.JLabel fecha_hora_ingreso;
    public static javax.swing.JLabel fecha_nacimiento;
    private javax.swing.JButton gastos_btn_back;
    private javax.swing.JButton genetrar_Pdf;
    public static javax.swing.JLabel id_paciente;
    public static javax.swing.JLabel id_venta;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel paciente;
    public static javax.swing.JPanel producto_sobrante3;
    public static javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
