/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si;

import Controladores.Controladorventa;

/**
 *
 * @author Alexis
 */
public class Crudo extends javax.swing.JFrame {

    /**
     * Creates new form Crudo
     */
    public Crudo() {
        initComponents();
        Controladorventa.noduplicarcrudo=true;
this.setLocation(600, 60);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        CRUDO = new javax.swing.JPanel();
        crudo = new javax.swing.JButton();
        masdeunapiezacrudo = new javax.swing.JCheckBox();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        bones = new javax.swing.JButton();
        Taxi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        CRUDO.setBackground(new java.awt.Color(0, 51, 102));
        CRUDO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CRUDO.setLayout(null);

        crudo.setBackground(new java.awt.Color(255, 255, 255));
        crudo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        crudo.setForeground(new java.awt.Color(255, 0, 0));
        crudo.setText("pollo crudo");
        crudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudoActionPerformed(evt);
            }
        });
        CRUDO.add(crudo);
        crudo.setBounds(6, 54, 172, 80);

        masdeunapiezacrudo.setBackground(new java.awt.Color(0, 51, 102));
        masdeunapiezacrudo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        masdeunapiezacrudo.setForeground(new java.awt.Color(255, 255, 255));
        masdeunapiezacrudo.setText("Agregar más de una pieza");
        CRUDO.add(masdeunapiezacrudo);
        masdeunapiezacrudo.setBounds(161, 6, 325, 36);

        jButton42.setBackground(new java.awt.Color(255, 255, 255));
        jButton42.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 0, 0));
        jButton42.setText("Medio pollo");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton42);
        jButton42.setBounds(230, 50, 170, 81);

        jButton43.setBackground(new java.awt.Color(255, 255, 255));
        jButton43.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 0, 0));
        jButton43.setText("Media pechuga");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton43);
        jButton43.setBounds(430, 50, 160, 81);

        jButton44.setBackground(new java.awt.Color(255, 255, 255));
        jButton44.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 0, 0));
        jButton44.setText("Pechuga");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton44);
        jButton44.setBounds(430, 150, 160, 77);

        jButton45.setBackground(new java.awt.Color(255, 255, 255));
        jButton45.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 0, 0));
        jButton45.setText("Hua completo");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton45);
        jButton45.setBounds(230, 150, 170, 76);

        jButton46.setBackground(new java.awt.Color(255, 255, 255));
        jButton46.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 0, 0));
        jButton46.setText("Pierna completa");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton46);
        jButton46.setBounds(10, 150, 172, 77);

        jButton47.setBackground(new java.awt.Color(255, 255, 255));
        jButton47.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 0, 0));
        jButton47.setText("Muslo");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton47);
        jButton47.setBounds(10, 240, 170, 74);

        jButton48.setBackground(new java.awt.Color(255, 255, 255));
        jButton48.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 0, 0));
        jButton48.setText("Pierna");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton48);
        jButton48.setBounds(230, 240, 170, 74);

        jButton49.setBackground(new java.awt.Color(255, 255, 255));
        jButton49.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 0, 0));
        jButton49.setText("Ala");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton49);
        jButton49.setBounds(430, 240, 158, 74);

        jButton50.setBackground(new java.awt.Color(255, 255, 255));
        jButton50.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 0, 0));
        jButton50.setText("Cabeza");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton50);
        jButton50.setBounds(430, 330, 160, 70);

        jButton51.setBackground(new java.awt.Color(255, 255, 255));
        jButton51.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 0, 0));
        jButton51.setText("Cadera");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton51);
        jButton51.setBounds(230, 330, 170, 70);

        jButton52.setBackground(new java.awt.Color(255, 255, 255));
        jButton52.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 0, 0));
        jButton52.setText("Huacal");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton52);
        jButton52.setBounds(10, 330, 170, 75);

        jButton53.setBackground(new java.awt.Color(255, 255, 255));
        jButton53.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 0, 0));
        jButton53.setText("Molleja");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton53);
        jButton53.setBounds(10, 420, 170, 69);

        jButton54.setBackground(new java.awt.Color(255, 255, 255));
        jButton54.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 0, 0));
        jButton54.setText("Patas");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton54);
        jButton54.setBounds(230, 420, 170, 69);

        jButton55.setBackground(new java.awt.Color(255, 255, 255));
        jButton55.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 0, 0));
        jButton55.setText("Pech./ bisteck");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        CRUDO.add(jButton55);
        jButton55.setBounds(430, 420, 160, 69);

        bones.setBackground(new java.awt.Color(255, 255, 255));
        bones.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bones.setForeground(new java.awt.Color(255, 0, 0));
        bones.setText("Huesitos");
        bones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonesActionPerformed(evt);
            }
        });
        CRUDO.add(bones);
        bones.setBounds(10, 510, 160, 40);

        Taxi.setBackground(new java.awt.Color(255, 255, 255));
        Taxi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Taxi.setForeground(new java.awt.Color(255, 0, 0));
        Taxi.setText("Taxi");
        Taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxiActionPerformed(evt);
            }
        });
        CRUDO.add(Taxi);
        Taxi.setBounds(230, 510, 170, 70);

        jTabbedPane1.addTab("CRUDO", CRUDO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonesActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Huesito","Escribe la cantidad en pesos");  new Calculadora().setVisible(true); }else{   Calculadora enviar = new Calculadora("Huesito","Escribe la cantidad en pesos"); new Calculadora().setVisible(true);   }
    }//GEN-LAST:event_bonesActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        if(masdeunapiezacrudo.isSelected()){ Calculadora enviar = new Calculadora("Pechuga en bisteck","Escribe la cantidad");   new Calculadora().setVisible(true); }else{   Controladorventa enviars = new Controladorventa("Pechuga en bisteck",1);  }
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        if(masdeunapiezacrudo.isSelected()){ Calculadora enviar = new Calculadora("Patas","Escribe la cantidad");  new Calculadora().setVisible(true);     }else{   Controladorventa enviars = new Controladorventa("Patas",1);}
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Molleja","Escribe la cantidad");    new Calculadora().setVisible(true);  }else{ Controladorventa enviars = new Controladorventa("Molleja",1);   }
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        if(masdeunapiezacrudo.isSelected()){   Calculadora enviar = new Calculadora("Huacal","Escribe la cantidad");  new Calculadora().setVisible(true);}else{ Controladorventa enviars = new Controladorventa("Huacal",1);  }
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Cadera","Escribe la cantidad"); new Calculadora().setVisible(true); }else{  Controladorventa enviars = new Controladorventa("Cadera",1); }
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Cabeza","Escribe la cantidad");   new Calculadora().setVisible(true);  }else{    Controladorventa enviars = new Controladorventa("Cabeza",1);     }
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        if(masdeunapiezacrudo.isSelected()){   Calculadora enviar = new Calculadora("Ala","Escribe la cantidad"); new Calculadora().setVisible(true);  }else{   Controladorventa enviars = new Controladorventa("Ala",1); }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        if(masdeunapiezacrudo.isSelected()){   Calculadora enviar = new Calculadora("Pierna","Escribe la cantidad"); new Calculadora().setVisible(true);   }else{    Controladorventa enviars = new Controladorventa("Pierna",1);}
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Muslo","Escribe la cantidad");  new Calculadora().setVisible(true);     }else{ Controladorventa enviars = new Controladorventa("Muslo",1);}
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Pierna completa","Escribe la cantidad"); new Calculadora().setVisible(true); }else{  Controladorventa enviars = new Controladorventa("Pierna completa",1); }
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Huacal completo","Escribe la cantidad");new Calculadora().setVisible(true);  }else{ Controladorventa enviars = new Controladorventa("Huacal completo",1);}
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Pechuga","Escribe la cantidad");new Calculadora().setVisible(true); }else{ Controladorventa enviars = new Controladorventa("Pechuga",1);}
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        if(masdeunapiezacrudo.isSelected()){   Controladorventa enviars = new Controladorventa((float)Controladorventa.medio, "Pechuga");   }else{  Controladorventa enviars = new Controladorventa((float)Controladorventa.medio, "Pechuga");}
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        if(masdeunapiezacrudo.isSelected()){Calculadora enviar = new Calculadora("Medio pollo","Escribe la cantidad");new Calculadora().setVisible(true);}else{ Controladorventa enviars = new Controladorventa(1, "Medio pollo"); }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void crudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudoActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("pollo crudo","Escribe la cantidad");new Calculadora().setVisible(true); }else{ Controladorventa enviars = new Controladorventa("pollo crudo",1);  }
    }//GEN-LAST:event_crudoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       Controladorventa.noduplicarcrudo=false;
    }//GEN-LAST:event_formWindowClosed

    private void TaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxiActionPerformed
        if(masdeunapiezacrudo.isSelected()){  Calculadora enviar = new Calculadora("Taxi","Escribe la cantidad en pesos");  new Calculadora().setVisible(true); }else{   Calculadora enviar = new Calculadora("Taxi","Escribe la cantidad en pesos"); new Calculadora().setVisible(true);   }
    }//GEN-LAST:event_TaxiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CRUDO;
    private javax.swing.JButton Taxi;
    private javax.swing.JButton bones;
    private javax.swing.JButton crudo;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox masdeunapiezacrudo;
    // End of variables declaration//GEN-END:variables
}
