/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si;
import Controladores.Controladorventa;
import Controladores.Controladorinventarioutilidades;
import Modelos.Modeloinventarioutilidades;
import Modelos.Modeloventa;
import javax.swing.JOptionPane;

/** 
 *
 * @author Alexis
 */
public class utilidades extends javax.swing.JFrame {

    /**
     * Creates new form Inventarioventas
     */
    public utilidades() {
        initComponents();
         Controladorventa.noduplicat_utilidades=true;
        Controladorinventarioutilidades.metodos_al_iniciar_inventarioventas();
             this.setLocationRelativeTo(null); // CENTRAR FORMULARIO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        Administrador = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        fechainicial = new com.toedter.calendar.JDateChooser();
        jLabel99 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        fechafinal = new com.toedter.calendar.JDateChooser();
        buscarventasporfecha = new javax.swing.JButton();
        totalventarealizada = new javax.swing.JLabel();
        totalutilidades = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        gastos_btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Administrador.setBackground(new java.awt.Color(135, 193, 193));
        Administrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Administrador.setDoubleBuffered(false);
        Administrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(135, 193, 193));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 24))); // NOI18N
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechainicial.setBackground(new java.awt.Color(135, 193, 193));
        fechainicial.setForeground(new java.awt.Color(0, 96, 255));
        fechainicial.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jPanel23.add(fechainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 40));

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel99.setText("Desde");
        jPanel23.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jLabel91.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel91.setText("Hasta");
        jPanel23.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 60, 50));

        fechafinal.setBackground(new java.awt.Color(135, 193, 193));
        fechafinal.setForeground(new java.awt.Color(0, 96, 255));
        fechafinal.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jPanel23.add(fechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 190, 40));

        buscarventasporfecha.setBackground(new java.awt.Color(255, 255, 255));
        buscarventasporfecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscarventasporfecha.setForeground(new java.awt.Color(255, 0, 0));
        buscarventasporfecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/image/magnifier.png"))); // NOI18N
        buscarventasporfecha.setToolTipText("Buscar");
        buscarventasporfecha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buscarventasporfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarventasporfechaActionPerformed(evt);
            }
        });
        jPanel23.add(buscarventasporfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 130, 40));

        totalventarealizada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalventarealizada.setText("Total de utilidades");
        jPanel23.add(totalventarealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 190, 30));

        totalutilidades.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalutilidades.setText("00.00");
        jPanel23.add(totalutilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 160, 30));

        jTable2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel23.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 800, 280));

        Administrador.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 830, 420));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel93.setText("Utilidades");

        gastos_btn_back.setBackground(new java.awt.Color(255, 255, 255));
        gastos_btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gastos_btn_back.setForeground(new java.awt.Color(255, 0, 0));
        gastos_btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/salir-flecha-derecha (1).png"))); // NOI18N
        gastos_btn_back.setText("Regresar");
        gastos_btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastos_btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(gastos_btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addComponent(gastos_btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Administrador.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gastos_btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastos_btn_backActionPerformed
          dispose();
    }//GEN-LAST:event_gastos_btn_backActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controladorventa.noduplicat_utilidades=false;
    }//GEN-LAST:event_formWindowClosed

    private void buscarventasporfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarventasporfechaActionPerformed
        Controladorinventarioutilidades.botonbuscarventas_porfecha();
    }//GEN-LAST:event_buscarventasporfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utilidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Administrador;
    public static javax.swing.JButton buscarventasporfecha;
    public static com.toedter.calendar.JDateChooser fechafinal;
    public static com.toedter.calendar.JDateChooser fechainicial;
    private javax.swing.JButton gastos_btn_back;
    public static javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    public static javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JLabel totalutilidades;
    public static javax.swing.JLabel totalventarealizada;
    // End of variables declaration//GEN-END:variables
}
