/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si;

import Controladores.Controlador_venta_a_credito;
import Controladores.Controladorventa;

/**
 *
 * @author aleks
 */
public class Ventas_a_credito extends javax.swing.JFrame {

    /**
     * Creates new form Ventas_a_credito
     */
    public Ventas_a_credito() {
        initComponents();
        Controladorventa.noduplicar_vista_de_ventas_a_credito=true;
        Controlador_venta_a_credito.ver_ventas_a_credito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelbusqueda = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_ventas_a_credito = new javax.swing.JTable();
        veridventas = new javax.swing.JButton();
        jLabel93 = new javax.swing.JLabel();
        gastos_btn_back = new javax.swing.JButton();
        pendiente = new javax.swing.JLabel();
        labelventa = new javax.swing.JLabel();
        idventa = new javax.swing.JLabel();
        labeltotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        labelpendiente = new javax.swing.JLabel();
        abono = new javax.swing.JLabel();
        labelabono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(135, 193, 193));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbusqueda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelbusqueda.setText("Buscar por nombre");
        jPanel1.add(labelbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 50));

        busqueda.setBackground(new java.awt.Color(135, 193, 193));
        busqueda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        busqueda.setToolTipText("");
        busqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaKeyReleased(evt);
            }
        });
        jPanel1.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 40));

        tabla_ventas_a_credito.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tabla_ventas_a_credito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_ventas_a_credito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_ventas_a_creditoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabla_ventas_a_credito);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1091, 174));

        veridventas.setBackground(new java.awt.Color(255, 255, 255));
        veridventas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        veridventas.setForeground(new java.awt.Color(0, 153, 153));
        veridventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/flecha-hacia-la-izquierda (1).png"))); // NOI18N
        veridventas.setText("Pagar venta");
        veridventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veridventasActionPerformed(evt);
            }
        });
        jPanel1.add(veridventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 285, 240, -1));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel93.setText("            Ventas a credito");
        jPanel1.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 6, 344, 60));

        gastos_btn_back.setBackground(new java.awt.Color(255, 255, 255));
        gastos_btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gastos_btn_back.setForeground(new java.awt.Color(255, 0, 0));
        gastos_btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/IconosJava/salir-flecha-derecha (1).png"))); // NOI18N
        gastos_btn_back.setText("Regresar");
        gastos_btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastos_btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(gastos_btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 17, 150, -1));

        pendiente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pendiente.setForeground(new java.awt.Color(0, 0, 0));
        pendiente.setText("Venta");
        jPanel1.add(pendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 110, 30));

        labelventa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelventa.setForeground(new java.awt.Color(0, 0, 0));
        labelventa.setText("Venta");
        jPanel1.add(labelventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 30));

        idventa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idventa.setForeground(new java.awt.Color(0, 0, 0));
        idventa.setText("Venta");
        jPanel1.add(idventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, 30));

        labeltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeltotal.setForeground(new java.awt.Color(0, 0, 0));
        labeltotal.setText("Total original");
        jPanel1.add(labeltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("Venta");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 100, 30));

        labelpendiente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelpendiente.setForeground(new java.awt.Color(0, 0, 0));
        labelpendiente.setText("Pendiente");
        jPanel1.add(labelpendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 110, 30));

        abono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        abono.setForeground(new java.awt.Color(0, 0, 0));
        abono.setText("Abono");
        jPanel1.add(abono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, 30));

        labelabono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelabono.setForeground(new java.awt.Color(0, 0, 0));
        labelabono.setText("Abono");
        jPanel1.add(labelabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyReleased
      Controlador_venta_a_credito.consulta_de_ventas_a_credito(busqueda.getText());
    }//GEN-LAST:event_busquedaKeyReleased

    private void veridventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veridventasActionPerformed
       Controlador_venta_a_credito.pagar_venta(Float.parseFloat(total.getText().substring(1)),Float.parseFloat(abono.getText().substring(1)),Float.parseFloat(pendiente.getText().substring(1)),Integer.parseInt(idventa.getText()));
    }//GEN-LAST:event_veridventasActionPerformed

    private void gastos_btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastos_btn_backActionPerformed
        dispose();
    }//GEN-LAST:event_gastos_btn_backActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Controladorventa.noduplicar_vista_de_ventas_a_credito=false;
    }//GEN-LAST:event_formWindowClosed

    private void tabla_ventas_a_creditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_ventas_a_creditoMouseClicked
    Controlador_venta_a_credito.ver_descrpcion_venta_a_credito();
    }//GEN-LAST:event_tabla_ventas_a_creditoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas_a_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas_a_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas_a_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas_a_credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas_a_credito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel abono;
    public static javax.swing.JTextField busqueda;
    private javax.swing.JButton gastos_btn_back;
    public static javax.swing.JLabel idventa;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JLabel labelabono;
    public static javax.swing.JLabel labelbusqueda;
    public static javax.swing.JLabel labelpendiente;
    public static javax.swing.JLabel labeltotal;
    public static javax.swing.JLabel labelventa;
    public static javax.swing.JLabel pendiente;
    public static javax.swing.JTable tabla_ventas_a_credito;
    public static javax.swing.JLabel total;
    public static javax.swing.JButton veridventas;
    // End of variables declaration//GEN-END:variables
}
